<a href="https://colab.research.google.com/github/fatouu50/tickit-database-analysis/blob/main/TICKIT_database_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

buyer = pd.read_csv("tickit_public_buyer.txt", sep="|")
seller = pd.read_csv("tickit_public_seller.txt", sep="|")
venue = pd.read_csv("tickit_public_venue.txt", sep="|")
category = pd.read_csv("tickit_public_category.txt", sep="|")
event = pd.read_csv("tickit_public_event.txt", sep="|")
listing = pd.read_csv("tickit_public_listing.txt", sep="|")
sale = pd.read_csv("tickit_public_sale.txt", sep="|")

In [2]:
tables = {
    "buyer": buyer,
    "seller": seller,
    "venue": venue,
    "category": category,
    "event": event,
    "listing": listing,
    "sale": sale
}

for name, df in tables.items():
    print(f"--- {name} ---")
    print(df.shape)
    print(df.head(2))
    print()

--- buyer ---
(49990, 18)
   buyerid  username firstname lastname        city state  \
0        1  JSG99FHE    Rafael   Taylor        Kent    WA
1        3  IFT66TXU      Lars  Ratliff  High Point    ME

                                           email           phone  likesports  \
0  Etiam.laoreet.libero@sodalesMaurisblandit.edu  (664) 602-4412       False
1    amet.faucibus.ut@condimentumegetvolutpat.ca  (624) 767-2465       False

   liketheatre  likeconcerts  likejazz  likeclassical  likeopera  likerock  \
0        False         False      True          False      False      True
1        False         False      True          False      False      True

   likevegas  likebroadway  likemusicals
0       True          True          True
1       True          True          True

--- seller ---
(49990, 9)
   sellerid  username firstname lastname        city state  \
0         1  JSG99FHE    Rafael   Taylor        Kent    WA
1         3  IFT66TXU      Lars  Ratliff  High Point    ME

                                           email           phone        tin
0  Etiam.laoreet.libero@sodalesMaurisblandit.edu  (664) 602-4412  722924618
1    amet.faucibus.ut@condimentumegetvolutpat.ca  (624) 767-2465  425620778

--- venue ---
(205, 5)
   venueid                  venuename    venuecity venuestate  venueseats
0        2      Columbus Crew Stadium     Columbus         OH         0.0
1        4  CommunityAmerica Ballpark  Kansas City         KS         0.0

--- category ---
(11, 4)
   catid catgroup catname                   catdesc
0      1   Sports     MLB     Major League Baseball
1      3   Sports     NFL  National Football League

--- event ---
(8798, 5)
   eventid  venueid  catid              eventname                   starttime
0      423      303      8  La Damnation de Faust  2008-01-01 19:30:00.000000
1     1334      208      6         The King and I  2008-01-01 14:30:00.000000

--- listing ---
(192497, 7)
   listid  sellerid  eventid  numtickets  priceperticket  totalprice  \
0     483     11556     5156           8            47.0       376.0
1     724     35016     3468          10            40.0       400.0

                     listtime
0  2008-01-01 05:54:44.000000
1  2008-01-01 03:32:37.000000

--- sale ---
(172456, 9)
   saleid  listid  sellerid  buyerid  eventid  qtysold  pricepaid  commission  \
0   65082   73790     20429      451     1150        4      472.0        70.8
1   97197  110942     43282      515     7003        2      708.0       106.2

                     saletime
0  2008-01-01 06:06:57.000000
1  2008-01-01 02:30:52.000000

In [3]:
buyer.head()

,buyerid,username,firstname,lastname,city,state,email,phone,likesports,liketheatre,likeconcerts,likejazz,likeclassical,likeopera,likerock,likevegas,likebroadway,likemusicals
0,1,JSG99FHE,Rafael,Taylor,Kent,WA,Etiam.laoreet.libero@sodalesMaurisblandit.edu,(664) 602-4412,False,False,False,True,False,False,True,True,True,True
1,3,IFT66TXU,Lars,Ratliff,High Point,ME,amet.faucibus.ut@condimentumegetvolutpat.ca,(624) 767-2465,False,False,False,True,False,False,True,True,True,True
2,4,XDZ38RDD,Barry,Roy,Omaha,AB,sed@lacusUtnec.ca,(355) 452-8168,False,False,False,False,True,False,True,True,False,False
3,5,AEB55QTM,Reagan,Hodge,Forest Lake,NS,Cum@accumsan.com,(476) 519-9131,False,False,False,False,False,True,False,True,True,False
4,215,MVZ73SEM,Daquan,Lang,Half Moon Bay,NL,Nunc.mauris@mattis.ca,(323) 413-1924,True,True,True,True,False,False,False,True,True,True

In [4]:
seller.head()

,sellerid,username,firstname,lastname,city,state,email,phone,tin
0,1,JSG99FHE,Rafael,Taylor,Kent,WA,Etiam.laoreet.libero@sodalesMaurisblandit.edu,(664) 602-4412,722924618
1,3,IFT66TXU,Lars,Ratliff,High Point,ME,amet.faucibus.ut@condimentumegetvolutpat.ca,(624) 767-2465,425620778
2,4,XDZ38RDD,Barry,Roy,Omaha,AB,sed@lacusUtnec.ca,(355) 452-8168,585214629
3,5,AEB55QTM,Reagan,Hodge,Forest Lake,NS,Cum@accumsan.com,(476) 519-9131,741169497
4,215,MVZ73SEM,Daquan,Lang,Half Moon Bay,NL,Nunc.mauris@mattis.ca,(323) 413-1924,865908512

In [5]:
venue.head()

   venueid                   venuename      venuecity venuestate  venueseats
0        2       Columbus Crew Stadium       Columbus         OH         0.0
1        4   CommunityAmerica Ballpark    Kansas City         KS         0.0
2        5            Gillette Stadium     Foxborough         MA     68756.0
3        7                   BMO Field        Toronto         ON         0.0
4        9  Dick's Sporting Goods Park  Commerce City         CO         0.0

In [6]:
category.head()

   catid  catgroup    catname                                     catdesc
0      1    Sports        MLB                       Major League Baseball
1      3    Sports        NFL                    National Football League
2      6     Shows   Musicals                             Musical theatre
3      8     Shows      Opera                   All opera and light opera
4     11  Concerts  Classical  All symphony, concerto, and choir concerts

In [7]:
listing.head()

,listid,sellerid,eventid,numtickets,priceperticket,totalprice,listtime
0,483,11556,5156,8,47.0,376.0,2008-01-01 05:54:44.000000
1,724,35016,3468,10,40.0,400.0,2008-01-01 03:32:37.000000
2,1315,37302,920,9,126.0,1134.0,2008-01-01 04:05:41.000000
3,1825,45077,3181,16,118.0,1888.0,2008-01-01 01:16:37.000000
4,4118,40141,5624,16,43.0,688.0,2008-01-01 03:10:06.000000

In [8]:
event.head()

   eventid  venueid  catid              eventname                   starttime
0      423      303      8  La Damnation de Faust  2008-01-01 19:30:00.000000
1     1334      208      6         The King and I  2008-01-01 14:30:00.000000
2     1376      235      6         The King and I  2008-01-01 14:30:00.000000
3     2099      211      7            The Bacchae  2008-01-01 19:30:00.000000
4     4850       91      9      Zappa Plays Zappa  2008-01-01 14:00:00.000000

In [9]:
sale.head()

,saleid,listid,sellerid,buyerid,eventid,qtysold,pricepaid,commission,saletime
0,65082,73790,20429,451,1150,4,472.0,70.80,2008-01-01 06:06:57.000000
1,97197,110942,43282,515,7003,2,708.0,106.20,2008-01-01 02:30:52.000000
2,110328,126347,6955,394,6213,1,347.0,52.05,2008-01-01 01:00:19.000000
3,165890,222879,2186,664,6870,2,4192.0,628.80,2008-01-01 12:59:34.000000
4,7011,7613,5933,1503,4515,1,177.0,26.55,2008-01-02 01:52:35.000000